"""Configuration: where credentials live and which tricounts are known.

Config is a small human-editable TOML file at ``~/.config/tricount-flow/config.toml``
(override the whole directory with ``TRICOUNT_FLOW_HOME``). The device credential
blob generated by ``tricount-api`` lives beside it and is never committed.
"""

from __future__ import annotations

import os
import tomllib
from dataclasses import dataclass, field
from pathlib import Path
from urllib.parse import urlparse

import tomli_w


def config_dir() -> Path:
    override = os.environ.get("TRICOUNT_FLOW_HOME")
    if override:
        return Path(override).expanduser()
    xdg = os.environ.get("XDG_CONFIG_HOME")
    base = Path(xdg).expanduser() if xdg else Path.home() / ".config"
    return base / "tricount-flow"


def config_path() -> Path:
    return config_dir() / "config.toml"


def default_credentials_path() -> Path:
    return config_dir() / "credentials.json"


class ConfigError(Exception):
    """Raised when the config is missing or malformed."""


@dataclass
class TricountEntry:
    link: str
    me: str | None = None


@dataclass
class Config:
    credentials_path: Path
    default: str | None = None
    tricounts: dict[str, TricountEntry] = field(default_factory=dict)

    # -- lookup helpers -------------------------------------------------
    def resolve_name(self, name: str | None) -> str:
        """Resolve a tricount alias.

        Precedence: explicit argument > ``$TRICOUNT`` env var > configured default.
        """
        name = name or os.environ.get("TRICOUNT") or self.default
        if not name:
            raise ConfigError(
                "No tricount specified and no default configured. Run `tricount init`."
            )
        if name not in self.tricounts:
            known = ", ".join(self.tricounts) or "(none)"
            raise ConfigError(f"Unknown tricount '{name}'. Configured: {known}.")
        return name

    def entry(self, name: str | None) -> tuple[str, TricountEntry]:
        resolved = self.resolve_name(name)
        return resolved, self.tricounts[resolved]

    def token_for(self, alias: str) -> str:
        return extract_token(self.tricounts[alias].link)

    def aliases_for_token(self, token: str, *, exclude: str | None = None) -> list[str]:
        """Aliases that already point at the same underlying tricount."""
        out = []
        for alias, entry in self.tricounts.items():
            if alias == exclude:
                continue
            try:
                if extract_token(entry.link) == token:
                    out.append(alias)
            except ConfigError:
                continue
        return out

    # -- mutations (pure; no network) -----------------------------------
    def upsert(self, alias: str, link: str, me: str | None = None) -> None:
        extract_token(link)  # validate the link shape early
        self.tricounts[alias] = TricountEntry(link=link, me=me)
        if self.default is None:
            self.default = alias

    def remove(self, alias: str) -> None:
        if alias not in self.tricounts:
            raise ConfigError(f"Unknown tricount '{alias}'.")
        del self.tricounts[alias]
        if self.default == alias:
            self.default = next(iter(self.tricounts), None)

    def rename(self, old: str, new: str) -> None:
        if old not in self.tricounts:
            raise ConfigError(f"Unknown tricount '{old}'.")
        if new == old:
            return
        if new in self.tricounts:
            raise ConfigError(f"A tricount named '{new}' already exists.")
        # Preserve insertion order by rebuilding the dict.
        self.tricounts = {(new if k == old else k): v for k, v in self.tricounts.items()}
        if self.default == old:
            self.default = new

    def set_default(self, alias: str) -> None:
        if alias not in self.tricounts:
            raise ConfigError(f"Unknown tricount '{alias}'.")
        self.default = alias

    def set_me(self, alias: str, member: str) -> None:
        if alias not in self.tricounts:
            raise ConfigError(f"Unknown tricount '{alias}'.")
        self.tricounts[alias].me = member


def load() -> Config:
    path = config_path()
    if not path.exists():
        return Config(credentials_path=default_credentials_path())
    with path.open("rb") as fh:
        data = tomllib.load(fh)

    cred = data.get("credentials_path")
    credentials_path = Path(cred).expanduser() if cred else default_credentials_path()

    tricounts: dict[str, TricountEntry] = {}
    for name, raw in (data.get("tricounts") or {}).items():
        if not isinstance(raw, dict) or "link" not in raw:
            raise ConfigError(f"Tricount '{name}' is missing a 'link' in {path}.")
        tricounts[name] = TricountEntry(link=raw["link"], me=raw.get("me"))

    return Config(
        credentials_path=credentials_path,
        default=data.get("default"),
        tricounts=tricounts,
    )


def save(cfg: Config) -> Path:
    path = config_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    payload: dict[str, object] = {"credentials_path": str(cfg.credentials_path)}
    if cfg.default:
        payload["default"] = cfg.default
    payload["tricounts"] = {
        name: ({"link": e.link, "me": e.me} if e.me else {"link": e.link})
        for name, e in cfg.tricounts.items()
    }
    with path.open("wb") as fh:
        tomli_w.dump(payload, fh)
    try:
        path.chmod(0o600)
    except OSError:
        pass
    return path


def extract_token(link: str) -> str:
    """Turn a share link or raw token into the tricount public token.

    Accepts ``https://tricount.com/tXXXX``, ``tricount.com/tXXXX?foo=bar``,
    trailing slashes, or an already-bare ``tXXXX`` token.
    """
    value = link.strip()
    if not value:
        raise ConfigError("Empty tricount link.")
    if "/" in value:
        parsed = urlparse(value if "//" in value else "https://" + value)
        segments = [s for s in parsed.path.split("/") if s]
        if not segments:
            raise ConfigError(f"Could not find a token in link: {link!r}")
        value = segments[-1]
    return value
